### ISSUE TITLE
Implement Provisioning of Score

### ISSUE THREAD

**Issue by gokul472** [overture-stack/dms#6] opened 2020-09-02 18:27 UTC
## Objective
Create the interactive questions for Score service deployment, and deploy
- includes minio deployment

## Outcome
Should be able to configure Score and deploy it locally.

## Wiki Link
https://wiki.oicr.on.ca/display/OV/DMS+Installer+Technical+Specs#DMSInstallerTechnicalSpecs-TableofContents

**Comment by b-f-chan** [comment] 2021-01-07 15:57
Closing, duplicate of #37

**Closed by b-f-chan** 2021-01-07 15:57 UTC
Labels: canarie
