### ISSUE TITLE
Implement Provisioning for Song

### ISSUE THREAD

**Issue by gokul472** [overture-stack/dms#5] opened 2020-09-02 18:25 UTC
## Objective
Create the interactive questions for SONG service deployment, and deploy\
- inludes database deployment

## Outcome
Should be able to configure SONG and deploy it locally.

## Wiki Link
https://wiki.oicr.on.ca/display/OV/DMS+Installer+Technical+Specs#DMSInstallerTechnicalSpecs-TableofContents

**Comment by b-f-chan** [comment] 2020-11-04 14:39
Sprint 10 candidate - If EGO installer step is completed in Sprint 9, we may be able to parallelize work with EGO as the template.  @rtisma needs to setup the Gateway, in the meantime, perhaps @anncatton can take on the next component (e.g. SONG).  To be discussed in planning.

**Comment by b-f-chan** [comment] 2021-01-07 15:53
Closing, duplicate of #35

**Closed by b-f-chan** 2021-01-07 15:53 UTC
Labels: canarie
